### ISSUE TITLE
Post is deleted, but it stays in sidebar widget

### ISSUE THREAD

**Issue by TheRadialActive** [meitar/diasposter#4]
I deleted a diaspora\* post connected to an wordpress article: So the sidebar widget on the edit page says: "View post on Diaspora*"

Then I deleted the diaspora\* post, that was created to test the diasposter again. But I have no opportunity to share the article again on diaspora*. The link in the sidebar stays the same.

Maybe the plugin could check, if the post is available. Or the wordpress user has the opportunity to delete the link of the sidebar widget.

**Comment by fabacab** [comment]
I'm confused. What did you delete and when?

**Comment by TheRadialActive** [comment]
Excuse me, I try to explain it more understandable:
- I created an article in wordpress
- I published the article and ticked "Post to Diaspora"
- diasposter created the diaspora post
- I deleted the diaspora post on the pod

Problem: I wanted to "Post to Diaspora" again, but the diasposter widget in the sidebar of the wordpress article edit page said: "View post on Diaspora"

If you clicked that button, you got a 404 Error, because the diaspora post was deleted. 

The question is: How could I "Post on Diaspora" again?

**Comment by fabacab** [comment]
Oh, I understand now, thanks for clarifying.

The issue here is that Diasposter is not updated when you delete your post _on Diaspora_, so it still thinks the post is there. The information about the link is saved inside the WordPress post's meta field with the keys `diaspora_host` and `diaspora_post_id`. If you don't see meta fields in your WordPress post editing screen, [be sure you've enabled "Custom Fields" from the "Screen Options" menu, as described here](https://support.wordpress.com/screen-options/). You can then delete those two keys to make Diasposter "forget" about the post on Diaspora.

I don't like the idea of checking to ensure the post is still there on Diaspora whenever you load the post editing screen because it would add an extra HTTP request round-trip, which can be slow and blocks the UI, among other reasons.

If you had deleted your post _in your WordPress admin screen_, then Diasposter is smart enough to go and delete the post from your Diaspora pod, too. That's the preferred way of deleting posts for this exact reason.

Hope this helps!
